<?php

namespace App\Repositories\MemberInsights\Newsletters;

use App\Enums\MemberInsights\Newsletters\NewsletterRelationType;
use App\Framework\Support\Collection;
use App\Models\NewsletterRelation;
use App\Repositories\Repository;

class NewsletterRelationRepository extends Repository
{
    /**
     * Find all newsletters related to any of the given source newsletter IDs,
     * excluding newsletters already in the source set.
     *
     * @param int[] $newsletterIds
     * @return Collection<NewsletterRelation>
     */
    public function findRelatedTo(array $newsletterIds, int $siteId): Collection
    {
        if (empty($newsletterIds)) {
            return collect([]);
        }

        return NewsletterRelation::whereIn('newsletter_id', $newsletterIds)
            ->whereNotIn('related_newsletter_id', $newsletterIds)
            ->whereHas('relatedNewsletter', fn($q) => $q->where('site_id', $siteId)->where('active', true)
            )
            ->with(['relatedNewsletter', 'sourceNewsletter'])
            ->get();
    }

    /**
     * Upsert an auto-generated relationship edge.
     *
     * Manual edges (is_auto_generated = false) are never overwritten —
     * the UPDATE clause skips rows where is_auto_generated = false so
     * admin-entered UpsellPremium edges are always preserved.
     */
    public function upsertAutoGenerated(
        int $newsletterId,
        int $relatedNewsletterIds,
        NewsletterRelationType $relationType,
    ): void
    {
        NewsletterRelation::upsert(
            [
                [
                    'newsletter_id' => $newsletterId,
                    'related_newsletter_id' => $relatedNewsletterIds,
                    'relation_type' => $relationType->value,
                    'is_auto_generated' => true,
                    'priority' => 0,
                ],
            ],
            uniqueBy: ['newsletter_id', 'related_newsletter_id'],
            update: [
                'relation_type' => true,
                'updated_at' => true,
            ],
        );
    }

    protected function getModelClass(): string
    {
        return NewsletterRelation::class;
    }
}