@section('logic')
<?php
/**
 * Template: open-collab/admin/payouts/scheduled.php
 * Variables:
 *   $pendingPayouts — Collection of Payout models (status = pending, scheduler-generated)
 *   $upcomingRows   — array of [ user_id, currency, amount ] — eligible but not yet scheduled
 *   $terms          — PaymentTerms model
 *   $cutoffDate     — string  e.g. "05 Apr 2026"
 *   $site           — string
 *   $currentUser    — AuthenticatedUser
 */
?>
@endsection

@extends('open-collab/layouts/admin')

@section('content')

<div id="status-toast"
     style="position:fixed;bottom:24px;left:50%;transform:translateX(-50%);
            background:var(--navy);color:#fff;padding:9px 20px;border-radius:20px;
            font-size:.8rem;font-weight:500;opacity:0;transition:opacity .3s;
            z-index:300;pointer-events:none;"></div>

<!-- Terms summary bar -->
<div class="oc-card" style="margin-bottom:24px;padding:16px 20px;">
    <div style="display:flex;align-items:center;gap:32px;flex-wrap:wrap;">
        <div>
            <div style="font-size:.72rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--slate);margin-bottom:2px;">
                Payout Delay
            </div>
            <div style="font-weight:600;color:var(--navy);"><?= (int)($terms->payout_delay_days ?? 7) ?> days</div>
        </div>
        <div>
            <div style="font-size:.72rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--slate);margin-bottom:2px;">
                Minimum Payout
            </div>
            <div style="font-weight:600;color:var(--navy);">
                £<?= number_format((int)($terms->minimum_payout_amount ?? 5000) / 100, 2) ?>
            </div>
        </div>
        <div>
            <div style="font-size:.72rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--slate);margin-bottom:2px;">
                Eligibility Cutoff
            </div>
            <div style="font-weight:600;color:var(--navy);">
                Earned before <?= htmlspecialchars($cutoffDate) ?>
            </div>
        </div>
        <a href="/admin/payment-terms" class="oc-btn oc-btn--ghost oc-btn--sm" style="margin-left:auto;">
            Edit payment terms
        </a>
    </div>
</div>

<!-- Section 1: Already generated (scheduler ran) -->
<div class="oc-card" style="margin-bottom:24px;">
    <div class="oc-card__header">
        <div>
            <span class="oc-card__title">Scheduled Payouts</span>
            <div style="font-size:.75rem;color:var(--slate);margin-top:2px;">
                Generated by the scheduler — pending admin approval
            </div>
        </div>
        <span style="font-size:.72rem;background:var(--slate-pale);color:var(--slate);
                     padding:2px 8px;border-radius:10px;font-weight:600;">
            <?= count($pendingPayouts) ?>
        </span>
    </div>

    <?php if ($pendingPayouts->isEmpty()): ?>
        <div style="padding:40px 24px;text-align:center;color:var(--slate);">
            <svg viewBox="0 0 20 20" fill="currentColor" width="28"
                 style="opacity:.2;display:block;margin:0 auto 12px;">
                <path fill-rule="evenodd"
                      d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                      clip-rule="evenodd"/>
            </svg>
            <div style="font-size:.9rem;font-weight:500;">No scheduler-generated payouts pending</div>
            <div style="font-size:.8rem;margin-top:4px;">The scheduler hasn't created any pending payouts yet, or all
                have been processed.
            </div>
        </div>
    <?php else: ?>
        <table class="oc-table">
            <thead>
            <tr>
                <th>Payout ID</th>
                <th>Contributor</th>
                <th>Amount</th>
                <th>Currency</th>
                <th>Created</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($pendingPayouts as $payout): ?>
                <tr id="sched-row-<?= (int)$payout->id ?>">
                    <td style="font-family:monospace;font-size:.78rem;color:var(--slate);">
                        PAY-<?= str_pad($payout->id, 6, '0', STR_PAD_LEFT) ?>
                    </td>
                    <td>
                        <a href="/admin/contributors/<?= (int)$payout->user_id ?>"
                           style="font-weight:500;color:var(--navy);text-decoration:none;">
                            User #<?= (int)$payout->user_id ?>
                        </a>
                    </td>
                    <td style="font-weight:600;color:var(--navy);">
                        £<?= number_format((int)$payout->amount / 100, 2) ?>
                    </td>
                    <td style="font-size:.82rem;color:var(--slate);">
                        <?= htmlspecialchars(strtoupper($payout->currency ?? 'GBP')) ?>
                    </td>
                    <td style="font-size:.78rem;color:var(--slate);">
                        <?= $payout->created_at ? date('d M Y', strtotime($payout->created_at)) : '–' ?>
                    </td>
                    <td>
                        <div style="display:flex;gap:6px;">
                            <button onclick="forcePayout(<?= (int)$payout->id ?>, this)"
                                    class="oc-btn oc-btn--primary oc-btn--sm"
                                    title="Approve this payout now">
                                Force approve
                            </button>
                            <a href="/<?= $site ?>/open-collab/admin/payouts" class="oc-btn oc-btn--ghost oc-btn--sm">
                                Manage
                            </a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

<!-- Section 2: Upcoming eligible — not yet generated -->
<div class="oc-card">
    <div class="oc-card__header">
        <div>
            <span class="oc-card__title">Upcoming Eligible Payouts</span>
            <div style="font-size:.75rem;color:var(--slate);margin-top:2px;">
                Preview — not yet scheduled · Will be created on next scheduler run
            </div>
        </div>
        <div style="display:flex;align-items:center;gap:8px;">
            <span style="font-size:.72rem;background:#fef3c7;color:#92400e;
                         padding:2px 8px;border-radius:10px;font-weight:600;">
                Preview
            </span>
            <span style="font-size:.72rem;background:var(--slate-pale);color:var(--slate);
                         padding:2px 8px;border-radius:10px;font-weight:600;">
                <?= count($upcomingRows) ?>
            </span>
        </div>
    </div>

    <?php if (empty($upcomingRows)): ?>
        <div style="padding:40px 24px;text-align:center;color:var(--slate);">
            <svg viewBox="0 0 20 20" fill="currentColor" width="28"
                 style="opacity:.2;display:block;margin:0 auto 12px;">
                <path fill-rule="evenodd"
                      d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                      clip-rule="evenodd"/>
            </svg>
            <div style="font-size:.9rem;font-weight:500;">No upcoming eligible payouts</div>
            <div style="font-size:.8rem;margin-top:4px;">
                No contributors currently have balances above the
                £<?= number_format((int)($terms->minimum_payout_amount ?? 5000) / 100, 2) ?> threshold
                past the <?= (int)($terms->payout_delay_days ?? 7) ?>-day holding period.
            </div>
        </div>
    <?php else: ?>
        <div class="oc-alert oc-alert--info" style="margin:0 20px 16px;font-size:.8rem;">
            <svg viewBox="0 0 20 20" fill="currentColor" width="14">
                <path fill-rule="evenodd"
                      d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                      clip-rule="evenodd"/>
            </svg>
            These entries meet all eligibility criteria. They will be converted into pending payouts on the next
            scheduler run. Amounts already in an in-flight payout are excluded.
        </div>
        <table class="oc-table">
            <thead>
            <tr>
                <th>Contributor</th>
                <th>Currency</th>
                <th>Eligible Amount</th>
                <th>Eligible Date</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($upcomingRows as $row): ?>
                <tr>
                    <td>
                        <a href="/admin/contributors/<?= (int)$row['user_id'] ?>"
                           style="font-weight:500;color:var(--navy);text-decoration:none;">
                            User #<?= (int)$row['user_id'] ?>
                        </a>
                    </td>
                    <td style="font-size:.82rem;color:var(--slate);">
                        <?= htmlspecialchars($row['currency']) ?>
                    </td>
                    <td style="font-weight:600;color:var(--navy);">
                        <?= $row['currency'] === 'GBP' ? '£' : '$' ?><?= number_format((int)$row['amount'] / 100, 2) ?>
                    </td>
                    <td style="font-size:.78rem;color:var(--slate);">
                        <?= htmlspecialchars($cutoffDate) ?>
                    </td>
                    <td>
                        <span style="font-size:.72rem;background:#fef3c7;color:#92400e;
                                     border:1px solid #fde68a;border-radius:10px;padding:2px 8px;font-weight:600;">
                            Not yet scheduled
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

@endsection

@section('scripts')
<script>
    class ScheduledPayoutsManager {
        #site;
        #token;

        constructor(site, token) {
            this.#site = site;
            this.#token = token;
        }

        async forceApprove(id, btn) {
            if (!confirm('Force-approve this payout now?')) return;
            btn.disabled = true;
            btn.innerHTML = '<div class="oc-spinner"></div>';

            const res = await fetch(`/api/${this.#site}/open-collab/admin/payouts/${id}/approve`, {
                method: 'POST',
                headers: {Authorization: `Bearer ${this.#token()}`, Accept: 'application/json'},
            });
            const data = await res.json();
            if (res.ok) {
                this.#showToast('✓ Payout approved');
                document.getElementById(`sched-row-${id}`)?.remove();
            } else {
                this.#showToast(data.error || 'Failed', false);
                btn.disabled = false;
                btn.textContent = 'Force approve';
            }
        }

        #showToast(msg, ok = true) {
            const el = document.getElementById('status-toast');
            el.textContent = msg;
            el.style.background = ok ? 'var(--navy)' : 'var(--red)';
            el.style.opacity = '1';
            setTimeout(() => {
                el.style.opacity = '0';
            }, 2800);
        }
    }

    const manager = new ScheduledPayoutsManager(SITE, () => localStorage.getItem('oc_token') || '');

    // Shim for PHP-rendered onclick
    const forcePayout = (id, btn) => manager.forceApprove(id, btn);
</script>
@endsection