<?php

return [
    'defaults' => [
        'color' => [
            'primary' => '#1f2937',
            'secondary' => '#4b5563',
            'accent' => '#2563eb',
            'background' => '#ffffff',
            'surface' => '#f8fafc',
            'text' => '#111827',
            'muted' => '#6b7280',
            'border' => '#e5e7eb',
        ],
        'brand' => [
            'heading_color' => '#1f2937',
            'button_background' => '#1f2937',
            'button_text' => '#ffffff',
            'button_hover' => '#111827',
            'hero_text' => '#ffffff',
            'hero_muted' => '#f3f4f6',
            'hero_overlay' => 'linear-gradient(90deg, rgba(0, 0, 0, 0.72), rgba(0, 0, 0, 0.2))',
            'heading_transform' => 'none',
            'heading_letter_spacing' => 'normal',
            'card_radius' => '8px',
            'newsletter_background' => 'linear-gradient(135deg, #2563eb, #1d4ed8)',
            'newsletter_title' => '#ffffff',
            'newsletter_text' => 'rgba(255, 255, 255, 0.88)',
            'newsletter_badge_background' => 'rgba(255, 255, 255, 0.14)',
            'newsletter_badge_text' => '#ffffff',
            'newsletter_button_background' => '#1f2937',
            'newsletter_button_hover' => '#111827',
            'newsletter_button_text' => '#ffffff',
        ],
        'font' => [
            'heading' => 'Georgia, serif',
            'body' => 'Arial, sans-serif',
        ],
        'radius' => [
            'small' => '4px',
            'medium' => '8px',
            'large' => '16px',
        ],
        'spacing' => [
            'section' => '3rem',
            'gutter' => '1.5rem',
        ],
        'content' => [
            'max_width' => '1200px',
            'article_width' => '760px',
        ],
    ],

    'sites' => [
        'estate' => [
            'color' => ['primary' => '#172554', 'accent' => '#b78a3d', 'surface' => '#f8f5ef'],
            'brand' => ['heading_color' => '#172554', 'button_background' => '#172554', 'button_hover' => '#b78a3d', 'hero_overlay' => 'linear-gradient(90deg, rgba(23, 37, 84, 0.82), rgba(23, 37, 84, 0.18))'],
        ],
        'tech-weekly' => [
            'color' => ['primary' => '#111827', 'accent' => '#0891b2', 'surface' => '#f3f4f6'],
            'font' => ['heading' => 'Inter, Arial, sans-serif'],
            'brand' => ['heading_color' => '#111827', 'button_background' => '#111827', 'button_hover' => '#0891b2', 'heading_letter_spacing' => '-0.025em', 'card_radius' => '4px'],
        ],
        'wine-chronicle' => [
            'color' => ['primary' => '#4c0519', 'accent' => '#9f1239', 'surface' => '#fff7ed'],
            'font' => ['heading' => 'Garamond, Georgia, serif'],
            'brand' => ['heading_color' => '#4c0519', 'button_background' => '#4c0519', 'button_hover' => '#9f1239', 'hero_overlay' => 'linear-gradient(90deg, rgba(76, 5, 25, 0.86), rgba(76, 5, 25, 0.22))'],
        ],
        'vogue-noir' => [
            'color' => ['primary' => '#000000', 'accent' => '#a21caf', 'surface' => '#fafafa'],
            'font' => ['heading' => 'Didot, Georgia, serif'],
            'brand' => ['heading_color' => '#000000', 'button_background' => '#000000', 'button_hover' => '#a21caf', 'heading_transform' => 'uppercase', 'heading_letter_spacing' => '0.08em', 'card_radius' => '0px'],
            'radius' => ['small' => '0px', 'medium' => '0px', 'large' => '0px'],
        ],
        'taste-table' => [
            'color' => ['primary' => '#3f3f46', 'accent' => '#c2410c', 'surface' => '#fff7ed'],
            'font' => ['heading' => 'Georgia, serif'],
            'brand' => ['heading_color' => '#3f3f46', 'button_background' => '#3f3f46', 'button_hover' => '#c2410c', 'hero_overlay' => 'linear-gradient(90deg, rgba(63, 63, 70, 0.76), rgba(194, 65, 12, 0.18))', 'card_radius' => '14px'],
        ],
        'gamesradar' => [
            'color' => ['primary' => '#18181b', 'accent' => '#15803d', 'surface' => '#f4f4f5'],
            'font' => ['heading' => 'Inter, Arial, sans-serif'],
            'brand' => ['heading_color' => '#18181b', 'button_background' => '#18181b', 'button_hover' => '#15803d', 'heading_transform' => 'uppercase', 'heading_letter_spacing' => '0.035em', 'card_radius' => '4px'],
        ],
        'guitar-world' => [
            'color' => ['primary' => '#303036', 'accent' => '#991b1b', 'surface' => '#fafafa'],
            'font' => ['heading' => 'Arial Black, Arial, sans-serif', 'body' => 'Arial, sans-serif'],
            'brand' => [
                'heading_color' => '#303036',
                'button_background' => '#27272a',
                'button_hover' => '#7f1d1d',
                'hero_text' => '#ffffff',
                'hero_muted' => '#f4f4f5',
                'hero_overlay' => 'linear-gradient(90deg, rgba(0, 0, 0, 0.82), rgba(0, 0, 0, 0.24))',
                'heading_transform' => 'uppercase',
                'heading_letter_spacing' => '-0.02em',
                'card_radius' => '2px',
                'newsletter_background' => 'radial-gradient(circle at 86% 12%, rgba(255, 255, 255, 0.12), transparent 28%), linear-gradient(135deg, #3f3f46 0%, #27272a 52%, #7f1d1d 135%)',
                'newsletter_title' => '#f8fafc',
                'newsletter_text' => '#e4e4e7',
                'newsletter_badge_background' => 'rgba(153, 27, 27, 0.68)',
                'newsletter_badge_text' => '#ffffff',
                'newsletter_button_background' => '#27272a',
                'newsletter_button_hover' => '#7f1d1d',
                'newsletter_button_text' => '#ffffff',
            ],
            'radius' => ['small' => '2px', 'medium' => '4px', 'large' => '8px'],
        ],
        'test-ste' => [],
        'haven-hearth' => [
            'color' => ['primary' => '#3f3f46', 'accent' => '#92400e', 'surface' => '#fffbeb'],
            'font' => ['heading' => 'Georgia, serif'],
            'brand' => ['heading_color' => '#3f3f46', 'button_background' => '#3f3f46', 'button_hover' => '#92400e', 'card_radius' => '18px'],
        ],
        'gocompare' => [
            'color' => ['primary' => '#172554', 'accent' => '#15803d', 'surface' => '#eff6ff'],
            'font' => ['heading' => 'Inter, Arial, sans-serif'],
            'brand' => ['heading_color' => '#172554', 'button_background' => '#172554', 'button_hover' => '#15803d', 'card_radius' => '12px'],
        ],
        'golf-monthly' => [
            'color' => ['primary' => '#14532d', 'accent' => '#a16207', 'surface' => '#f0fdf4'],
            'font' => ['heading' => 'Georgia, serif'],
            'brand' => ['heading_color' => '#14532d', 'button_background' => '#14532d', 'button_hover' => '#a16207', 'hero_overlay' => 'linear-gradient(90deg, rgba(20, 83, 45, 0.82), rgba(20, 83, 45, 0.18))'],
        ],
        'horse-and-hound' => [
            'color' => ['primary' => '#422006', 'accent' => '#92400e', 'surface' => '#fffbeb'],
            'font' => ['heading' => 'Garamond, Georgia, serif'],
            'brand' => ['heading_color' => '#422006', 'button_background' => '#422006', 'button_hover' => '#92400e', 'hero_overlay' => 'linear-gradient(90deg, rgba(66, 32, 6, 0.82), rgba(66, 32, 6, 0.18))'],
        ],
        'global-wanderlust' => [
            'color' => ['primary' => '#164e63', 'accent' => '#0e7490', 'surface' => '#ecfeff'],
            'font' => ['heading' => 'Trebuchet MS, Arial, sans-serif'],
            'brand' => ['heading_color' => '#164e63', 'button_background' => '#164e63', 'button_hover' => '#0e7490', 'card_radius' => '16px'],
        ],
        'toms-guide' => [
            'color' => ['primary' => '#111827', 'accent' => '#1d4ed8', 'surface' => '#f8fafc'],
            'font' => ['heading' => 'Inter, Arial, sans-serif'],
            'brand' => ['heading_color' => '#111827', 'button_background' => '#111827', 'button_hover' => '#1d4ed8', 'heading_letter_spacing' => '-0.025em', 'card_radius' => '6px'],
        ],
        'the-week' => [
            'color' => ['primary' => '#1e3a8a', 'accent' => '#b91c1c', 'surface' => '#f8fafc'],
            'font' => ['heading' => 'Georgia, serif'],
            'brand' => ['heading_color' => '#1e3a8a', 'button_background' => '#1e3a8a', 'button_hover' => '#b91c1c', 'hero_overlay' => 'linear-gradient(90deg, rgba(30, 58, 138, 0.82), rgba(185, 28, 28, 0.18))'],
        ],
        'space-com' => [
            'color' => ['primary' => '#f8fafc', 'accent' => '#8b5cf6', 'background' => '#020617', 'surface' => '#0f172a', 'text' => '#f8fafc', 'muted' => '#94a3b8', 'border' => '#334155'],
            'font' => ['heading' => 'Arial Black, Arial, sans-serif'],
            'brand' => ['heading_color' => '#f8fafc', 'button_background' => '#7c3aed', 'button_hover' => '#a78bfa', 'button_text' => '#ffffff', 'hero_overlay' => 'linear-gradient(90deg, rgba(2, 6, 23, 0.9), rgba(76, 29, 149, 0.28))', 'heading_transform' => 'uppercase', 'heading_letter_spacing' => '0.04em', 'card_radius' => '4px'],
        ],
        'soundwave' => [
            'color' => ['primary' => '#18181b', 'accent' => '#be185d', 'surface' => '#fafafa'],
            'font' => ['heading' => 'Arial Black, Arial, sans-serif'],
            'brand' => ['heading_color' => '#18181b', 'button_background' => '#18181b', 'button_hover' => '#be185d', 'heading_transform' => 'uppercase', 'heading_letter_spacing' => '0.06em', 'card_radius' => '0px'],
            'radius' => ['small' => '0px', 'medium' => '0px', 'large' => '4px'],
        ],
        'music-week' => [
            'color' => ['primary' => '#111827', 'accent' => '#6d28d9', 'surface' => '#f5f3ff'],
            'font' => ['heading' => 'Inter, Arial, sans-serif'],
            'brand' => ['heading_color' => '#111827', 'button_background' => '#111827', 'button_hover' => '#6d28d9', 'heading_transform' => 'uppercase', 'heading_letter_spacing' => '0.03em', 'card_radius' => '6px'],
        ],
        'money-week' => [
            'color' => ['primary' => '#052e16', 'accent' => '#15803d', 'surface' => '#f0fdf4'],
            'font' => ['heading' => 'Georgia, serif'],
            'brand' => ['heading_color' => '#052e16', 'button_background' => '#052e16', 'button_hover' => '#15803d', 'card_radius' => '2px'],
        ],
        'fourfour two' => [
            'color' => ['primary' => '#7f1d1d', 'accent' => '#b91c1c', 'surface' => '#fef2f2'],
            'font' => ['heading' => 'Arial Black, Arial, sans-serif'],
            'brand' => ['heading_color' => '#7f1d1d', 'button_background' => '#111827', 'button_hover' => '#b91c1c', 'heading_transform' => 'uppercase', 'heading_letter_spacing' => '-0.015em', 'card_radius' => '4px'],
        ],
    ],
];
