<?php

return [
    'site_enabled' => env('RBAC_SITE_ENABLED', true),

    'permissions' => [
        ['name' => 'Create Content', 'slug' => 'content.create', 'group' => 'content'],
        ['name' => 'Submit Content', 'slug' => 'content.submit', 'group' => 'content'],
        ['name' => 'Edit Own Content', 'slug' => 'content.edit_own', 'group' => 'content'],
        ['name' => 'Review Content', 'slug' => 'content.review', 'group' => 'content'],
        ['name' => 'Approve Content', 'slug' => 'content.approve', 'group' => 'content'],
        ['name' => 'Reject Content', 'slug' => 'content.reject', 'group' => 'content'],
        ['name' => 'Publish Content', 'slug' => 'content.publish', 'group' => 'content'],
        ['name' => 'View Pages', 'slug' => 'pages.view', 'group' => 'pages'],
        ['name' => 'Create Pages', 'slug' => 'pages.create', 'group' => 'pages'],
        ['name' => 'Edit Pages', 'slug' => 'pages.edit', 'group' => 'pages'],
        ['name' => 'Submit Pages For Approval', 'slug' => 'pages.submit_for_approval', 'group' => 'pages'],
        ['name' => 'Review Pages', 'slug' => 'pages.review', 'group' => 'pages'],
        ['name' => 'Approve Pages', 'slug' => 'pages.approve', 'group' => 'pages'],
        ['name' => 'Reject Pages', 'slug' => 'pages.reject', 'group' => 'pages'],
        ['name' => 'Hold Pages', 'slug' => 'pages.hold', 'group' => 'pages'],
        ['name' => 'Publish Pages', 'slug' => 'pages.publish', 'group' => 'pages'],
        ['name' => 'View Briefs', 'slug' => 'briefs.view', 'group' => 'briefs'],
        ['name' => 'Create Briefs', 'slug' => 'briefs.create', 'group' => 'briefs'],
        ['name' => 'Edit Briefs', 'slug' => 'briefs.edit', 'group' => 'briefs'],
        ['name' => 'Submit Briefs For Approval', 'slug' => 'briefs.submit_for_approval', 'group' => 'briefs'],
        ['name' => 'Review Briefs', 'slug' => 'briefs.review', 'group' => 'briefs'],
        ['name' => 'Approve Briefs', 'slug' => 'briefs.approve', 'group' => 'briefs'],
        ['name' => 'Reject Briefs', 'slug' => 'briefs.reject', 'group' => 'briefs'],
        ['name' => 'Hold Briefs', 'slug' => 'briefs.hold', 'group' => 'briefs'],
        ['name' => 'View Onboarding', 'slug' => 'onboarding.view', 'group' => 'onboarding'],
        ['name' => 'Override Onboarding', 'slug' => 'onboarding.override', 'group' => 'onboarding'],
        ['name' => 'Force Complete Onboarding', 'slug' => 'onboarding.force_complete', 'group' => 'onboarding'],
        ['name' => 'View Dashboard Widgets', 'slug' => 'dashboard.widgets.view', 'group' => 'dashboard'],
        ['name' => 'View Dashboard Payouts Widget', 'slug' => 'dashboard.payouts.view', 'group' => 'dashboard'],
        ['name' => 'View Dashboard Onboarding Widget', 'slug' => 'dashboard.onboarding.view', 'group' => 'dashboard'],
        ['name' => 'View Dashboard Content Queue Widget', 'slug' => 'dashboard.content_queue.view', 'group' => 'dashboard'],
        ['name' => 'Create Contract', 'slug' => 'contract.create', 'group' => 'contracts'],
        ['name' => 'Edit Contract', 'slug' => 'contract.edit', 'group' => 'contracts'],
        ['name' => 'Publish Contract', 'slug' => 'contract.publish', 'group' => 'contracts'],
        ['name' => 'Archive Contract', 'slug' => 'contract.archive', 'group' => 'contracts'],
        ['name' => 'View Contract', 'slug' => 'contract.view', 'group' => 'contracts'],
        ['name' => 'Sign Contract', 'slug' => 'contract.sign', 'group' => 'contracts'],
        ['name' => 'Create Guideline', 'slug' => 'guideline.create', 'group' => 'guidelines'],
        ['name' => 'Edit Guideline', 'slug' => 'guideline.edit', 'group' => 'guidelines'],
        ['name' => 'Publish Guideline', 'slug' => 'guideline.publish', 'group' => 'guidelines'],
        ['name' => 'Archive Guideline', 'slug' => 'guideline.archive', 'group' => 'guidelines'],
        ['name' => 'Acknowledge Guideline', 'slug' => 'guideline.acknowledge', 'group' => 'guidelines'],
        ['name' => 'Request Payout', 'slug' => 'payout.request', 'group' => 'finance'],
        ['name' => 'View Payout', 'slug' => 'payout.view', 'group' => 'finance'],
        ['name' => 'Approve Payout', 'slug' => 'payout.approve', 'group' => 'finance'],
        ['name' => 'Reject Payout', 'slug' => 'payout.reject', 'group' => 'finance'],
        ['name' => 'Mark Payout Paid', 'slug' => 'payout.mark_paid', 'group' => 'finance'],
        ['name' => 'View Ledger', 'slug' => 'ledger.view', 'group' => 'finance'],
        ['name' => 'Invite Creator', 'slug' => 'creator.invite', 'group' => 'creator_management'],
        ['name' => 'Remove Creator', 'slug' => 'creator.remove', 'group' => 'creator_management'],
        ['name' => 'Suspend Creator', 'slug' => 'creator.suspend', 'group' => 'creator_management'],
        ['name' => 'Manage Creator Roles', 'slug' => 'creator.manage_roles', 'group' => 'creator_management'],
        ['name' => 'View Contributor Details', 'slug' => 'contributor.details.view', 'group' => 'contributors'],
        ['name' => 'View Contributor Invitations', 'slug' => 'contributor.invitation.view', 'group' => 'contributors'],
        ['name' => 'Resend Contributor Invitations', 'slug' => 'contributor.invitation.resend', 'group' => 'contributors'],
        ['name' => 'Revoke Contributor Invitations', 'slug' => 'contributor.invitation.revoke', 'group' => 'contributors'],
        ['name' => 'View Contributor Capabilities', 'slug' => 'contributor.capabilities.view', 'group' => 'contributors'],
        ['name' => 'Manage Contributor Capabilities', 'slug' => 'contributor.capabilities.manage', 'group' => 'contributors'],
        ['name' => 'View Contributor Onboarding', 'slug' => 'contributor.onboarding.view', 'group' => 'contributors'],
        ['name' => 'View Contributor Activity', 'slug' => 'contributor.activity.view', 'group' => 'contributors'],
        ['name' => 'Manage Site', 'slug' => 'site.manage', 'group' => 'site_administration'],
        ['name' => 'Manage Site Members', 'slug' => 'site.members', 'group' => 'site_administration'],
        ['name' => 'Manage Site Roles', 'slug' => 'site.roles.manage', 'group' => 'site_administration'],
        ['name' => 'Manage Site Permissions', 'slug' => 'site.permissions.manage', 'group' => 'site_administration'],
        ['name' => 'View Violations', 'slug' => 'violation.view', 'group' => 'moderation'],
        ['name' => 'Record Violations', 'slug' => 'violation.record', 'group' => 'moderation'],
        ['name' => 'Resolve Violations', 'slug' => 'violation.resolve', 'group' => 'moderation'],
        ['name' => 'View Subscriptions', 'slug' => 'subscriptions.view', 'group' => 'subscriptions'],
        ['name' => 'Create Subscriptions', 'slug' => 'subscriptions.create', 'group' => 'subscriptions'],
        ['name' => 'Edit Subscriptions', 'slug' => 'subscriptions.edit', 'group' => 'subscriptions'],
        ['name' => 'Cancel Subscriptions', 'slug' => 'subscriptions.cancel', 'group' => 'subscriptions'],
        ['name' => 'Pause Subscriptions', 'slug' => 'subscriptions.pause', 'group' => 'subscriptions'],
        ['name' => 'Resume Subscriptions', 'slug' => 'subscriptions.resume', 'group' => 'subscriptions'],
        ['name' => 'Refund Subscriptions', 'slug' => 'subscriptions.refund', 'group' => 'subscriptions'],
        ['name' => 'Change Subscription Plan', 'slug' => 'subscriptions.change_plan', 'group' => 'subscriptions'],
        ['name' => 'Change Subscription Edition', 'slug' => 'subscriptions.change_edition', 'group' => 'subscriptions'],
        ['name' => 'Manage Subscription Payment Method', 'slug' => 'subscriptions.manage_payment_method', 'group' => 'subscriptions'],
        ['name' => 'View Subscription History', 'slug' => 'subscriptions.view_history', 'group' => 'subscriptions'],
        ['name' => 'View Subscription Plans', 'slug' => 'subscription_plans.view', 'group' => 'subscription_plans'],
        ['name' => 'Create Subscription Plans', 'slug' => 'subscription_plans.create', 'group' => 'subscription_plans'],
        ['name' => 'Edit Subscription Plans', 'slug' => 'subscription_plans.edit', 'group' => 'subscription_plans'],
        ['name' => 'Archive Subscription Plans', 'slug' => 'subscription_plans.archive', 'group' => 'subscription_plans'],
        ['name' => 'View Subscription Pricing', 'slug' => 'subscription_pricing.view', 'group' => 'subscription_pricing'],
        ['name' => 'Create Subscription Pricing', 'slug' => 'subscription_pricing.create', 'group' => 'subscription_pricing'],
        ['name' => 'Edit Subscription Pricing', 'slug' => 'subscription_pricing.edit', 'group' => 'subscription_pricing'],
        ['name' => 'Delete Subscription Pricing', 'slug' => 'subscription_pricing.delete', 'group' => 'subscription_pricing'],
        ['name' => 'View Issues', 'slug' => 'issues.view', 'group' => 'issues'],
        ['name' => 'Create Issues', 'slug' => 'issues.create', 'group' => 'issues'],
        ['name' => 'Edit Issues', 'slug' => 'issues.edit', 'group' => 'issues'],
        ['name' => 'Archive Issues', 'slug' => 'issues.archive', 'group' => 'issues'],
        ['name' => 'Schedule Issues', 'slug' => 'issues.schedule', 'group' => 'issues'],
        ['name' => 'Export Issues', 'slug' => 'issues.export', 'group' => 'issues'],
        ['name' => 'Mark Issues Delivered', 'slug' => 'issues.mark_delivered', 'group' => 'issues'],
        ['name' => 'View Vouchers', 'slug' => 'vouchers.view', 'group' => 'vouchers'],
        ['name' => 'Create Vouchers', 'slug' => 'vouchers.create', 'group' => 'vouchers'],
        ['name' => 'Edit Vouchers', 'slug' => 'vouchers.edit', 'group' => 'vouchers'],
        ['name' => 'Archive Vouchers', 'slug' => 'vouchers.archive', 'group' => 'vouchers'],
        ['name' => 'Assign Vouchers', 'slug' => 'vouchers.assign', 'group' => 'vouchers'],
        ['name' => 'Redeem Vouchers', 'slug' => 'vouchers.redeem', 'group' => 'vouchers'],
        ['name' => 'View CRM', 'slug' => 'crm.view', 'group' => 'crm'],
        ['name' => 'View CRM Members', 'slug' => 'crm.members.view', 'group' => 'crm'],
        ['name' => 'Create CRM Members', 'slug' => 'crm.members.create', 'group' => 'crm'],
        ['name' => 'Edit CRM Members', 'slug' => 'crm.members.edit', 'group' => 'crm'],
        ['name' => 'Archive CRM Members', 'slug' => 'crm.members.archive', 'group' => 'crm'],
        ['name' => 'Merge CRM Members', 'slug' => 'crm.members.merge', 'group' => 'crm'],
        ['name' => 'View CRM Subscriptions', 'slug' => 'crm.subscriptions.view', 'group' => 'crm'],
        ['name' => 'Edit CRM Subscriptions', 'slug' => 'crm.subscriptions.edit', 'group' => 'crm'],
        ['name' => 'Cancel CRM Subscriptions', 'slug' => 'crm.subscriptions.cancel', 'group' => 'crm'],
        ['name' => 'Pause CRM Subscriptions', 'slug' => 'crm.subscriptions.pause', 'group' => 'crm'],
        ['name' => 'Resume CRM Subscriptions', 'slug' => 'crm.subscriptions.resume', 'group' => 'crm'],
        ['name' => 'Change CRM Subscription Plan', 'slug' => 'crm.subscriptions.change_plan', 'group' => 'crm'],
        ['name' => 'Refund CRM Subscriptions', 'slug' => 'crm.subscriptions.refund', 'group' => 'crm'],
        ['name' => 'View CRM Notes', 'slug' => 'crm.notes.view', 'group' => 'crm'],
        ['name' => 'Create CRM Notes', 'slug' => 'crm.notes.create', 'group' => 'crm'],
        ['name' => 'Edit CRM Notes', 'slug' => 'crm.notes.edit', 'group' => 'crm'],
        ['name' => 'Delete CRM Notes', 'slug' => 'crm.notes.delete', 'group' => 'crm'],
        ['name' => 'View CRM Attachments', 'slug' => 'crm.attachments.view', 'group' => 'crm'],
        ['name' => 'Upload CRM Attachments', 'slug' => 'crm.attachments.upload', 'group' => 'crm'],
        ['name' => 'Delete CRM Attachments', 'slug' => 'crm.attachments.delete', 'group' => 'crm'],
        ['name' => 'View CRM Payment Methods', 'slug' => 'crm.payment_methods.view', 'group' => 'crm'],
        ['name' => 'Manage CRM Payment Methods', 'slug' => 'crm.payment_methods.manage', 'group' => 'crm'],
        ['name' => 'View CRM Duplicates', 'slug' => 'crm.duplicates.view', 'group' => 'crm'],
        ['name' => 'Merge CRM Duplicates', 'slug' => 'crm.duplicates.merge', 'group' => 'crm'],
        ['name' => 'Ignore CRM Duplicates', 'slug' => 'crm.duplicates.ignore', 'group' => 'crm'],
        ['name' => 'View CRM Segments', 'slug' => 'crm.segments.view', 'group' => 'crm'],
        ['name' => 'Create CRM Segments', 'slug' => 'crm.segments.create', 'group' => 'crm'],
        ['name' => 'Edit CRM Segments', 'slug' => 'crm.segments.edit', 'group' => 'crm'],
        ['name' => 'Delete CRM Segments', 'slug' => 'crm.segments.delete', 'group' => 'crm'],
    ],

    'roles' => [
        'site_admin' => [
            'name' => 'Site Admin',
            'is_system' => true,
            'permissions' => ['*'],
        ],
        'creator' => [
            'name' => 'Creator',
            'is_system' => true,
            'permissions' => [
                'content.create',
                'content.submit',
                'content.edit_own',
                'pages.create',
                'pages.submit_for_approval',
                'pages.edit',
                'payout.request',
                'contract.sign',
                'guideline.acknowledge',
                'onboarding.view',
            ],
        ],
        'reviewer' => [
            'name' => 'Reviewer',
            'is_system' => true,
            'permissions' => [
                'content.review',
                'content.reject',
                'content.approve',
                'pages.view',
                'pages.review',
                'pages.approve',
                'pages.reject',
                'pages.hold',
                'briefs.view',
                'briefs.review',
                'briefs.approve',
                'briefs.reject',
                'briefs.hold',
                'violation.view',
                'violation.record',
            ],
        ],
        'finance' => [
            'name' => 'Finance',
            'is_system' => true,
            'permissions' => ['payout.view', 'payout.approve', 'payout.reject', 'payout.mark_paid', 'ledger.view'],
        ],
        'legal' => [
            'name' => 'Legal',
            'is_system' => true,
            'permissions' => ['contract.create', 'contract.edit', 'contract.publish', 'contract.archive', 'contract.view', 'guideline.create', 'guideline.edit', 'guideline.publish', 'guideline.archive'],
        ],
        'brand_manager' => [
            'name' => 'Brand Manager',
            'is_system' => true,
            'permissions' => ['creator.invite', 'creator.manage_roles', 'onboarding.override', 'site.members', 'violation.view', 'violation.record', 'violation.resolve'],
        ],
        'subscription_admin' => [
            'name' => 'Subscription Admin',
            'is_system' => true,
            'permissions' => [
                'subscriptions.view',
                'subscriptions.create',
                'subscriptions.edit',
                'subscriptions.cancel',
                'subscriptions.pause',
                'subscriptions.resume',
                'subscriptions.refund',
                'subscriptions.change_plan',
                'subscriptions.change_edition',
                'subscriptions.manage_payment_method',
                'subscriptions.view_history',
                'subscription_plans.view',
                'subscription_plans.create',
                'subscription_plans.edit',
                'subscription_plans.archive',
                'subscription_pricing.view',
                'subscription_pricing.create',
                'subscription_pricing.edit',
                'subscription_pricing.delete',
                'issues.view',
                'issues.create',
                'issues.edit',
                'issues.archive',
                'issues.schedule',
                'issues.export',
                'issues.mark_delivered',
                'vouchers.view',
                'vouchers.create',
                'vouchers.edit',
                'vouchers.archive',
                'vouchers.assign',
                'vouchers.redeem',
            ],
        ],
        'crm_agent' => [
            'name' => 'CRM Agent',
            'is_system' => true,
            'permissions' => [
                'crm.view',
                'crm.members.view',
                'crm.members.edit',
                'crm.subscriptions.view',
                'crm.notes.view',
                'crm.notes.create',
                'crm.notes.edit',
                'crm.notes.delete',
                'crm.attachments.view',
            ],
        ],
        'crm_manager' => [
            'name' => 'CRM Manager',
            'is_system' => true,
            'permissions' => [
                'crm.view',
                'crm.members.view',
                'crm.members.create',
                'crm.members.edit',
                'crm.members.archive',
                'crm.members.merge',
                'crm.subscriptions.view',
                'crm.subscriptions.edit',
                'crm.subscriptions.cancel',
                'crm.subscriptions.pause',
                'crm.subscriptions.resume',
                'crm.subscriptions.change_plan',
                'crm.subscriptions.refund',
                'crm.notes.view',
                'crm.notes.create',
                'crm.notes.edit',
                'crm.notes.delete',
                'crm.attachments.view',
                'crm.attachments.upload',
                'crm.attachments.delete',
                'crm.payment_methods.view',
                'crm.payment_methods.manage',
                'crm.duplicates.view',
                'crm.duplicates.merge',
                'crm.duplicates.ignore',
                'crm.segments.view',
                'crm.segments.create',
                'crm.segments.edit',
                'crm.segments.delete',
            ],
        ],
        'finance_refunds' => [
            'name' => 'Finance/Refunds',
            'is_system' => true,
            'permissions' => [
                'crm.members.view',
                'crm.subscriptions.view',
                'crm.subscriptions.refund',
                'subscriptions.refund',
                'crm.payment_methods.view',
                'crm.payment_methods.manage',
            ],
        ],
    ],

    'legacy_role_map' => [
        'admin' => ['site_role' => 'site_admin', 'permissions' => ['*']],
        'agent' => ['site_role' => 'site_admin', 'permissions' => ['*']],
        'finance' => ['site_role' => 'finance', 'permissions' => ['payout.view', 'payout.approve', 'payout.reject', 'payout.mark_paid', 'ledger.view']],
        'legal' => ['site_role' => 'legal', 'permissions' => ['contract.create', 'contract.edit', 'contract.publish', 'contract.archive', 'contract.view', 'guideline.create', 'guideline.edit', 'guideline.publish', 'guideline.archive']],
        'creator' => ['site_role' => 'creator', 'permissions' => ['content.create', 'content.submit', 'content.edit_own', 'pages.create', 'pages.submit_for_approval', 'pages.edit', 'onboarding.view']],
        'contributor' => ['site_role' => 'creator', 'permissions' => ['content.create', 'content.submit', 'content.edit_own', 'pages.create', 'pages.submit_for_approval', 'pages.edit', 'payout.request', 'contract.sign', 'guideline.acknowledge', 'onboarding.view']],
        'reviewer' => ['site_role' => 'reviewer', 'permissions' => ['content.review', 'content.reject', 'content.approve', 'pages.view', 'pages.review', 'pages.reject', 'pages.approve', 'pages.hold', 'briefs.view', 'briefs.review', 'briefs.reject', 'briefs.approve', 'briefs.hold']],
        'editor' => ['site_role' => 'reviewer', 'permissions' => ['content.review', 'content.reject', 'content.approve', 'pages.view', 'pages.review', 'pages.reject', 'pages.approve', 'pages.hold', 'briefs.view', 'briefs.review', 'briefs.reject', 'briefs.approve', 'briefs.hold', 'violation.view', 'violation.record']],
    ],
];
