<?php

return [
    'site_enabled' => env('RBAC_SITE_ENABLED', true),

    'permissions' => [
        ['name' => 'Create Content', 'slug' => 'content.create', 'group' => 'content'],
        ['name' => 'Submit Content', 'slug' => 'content.submit', 'group' => 'content'],
        ['name' => 'Edit Own Content', 'slug' => 'content.edit_own', 'group' => 'content'],
        ['name' => 'Review Content', 'slug' => 'content.review', 'group' => 'content'],
        ['name' => 'Approve Content', 'slug' => 'content.approve', 'group' => 'content'],
        ['name' => 'Reject Content', 'slug' => 'content.reject', 'group' => 'content'],
        ['name' => 'Publish Content', 'slug' => 'content.publish', 'group' => 'content'],
        ['name' => 'View Pages', 'slug' => 'pages.view', 'group' => 'pages'],
        ['name' => 'Create Pages', 'slug' => 'pages.create', 'group' => 'pages'],
        ['name' => 'Edit Pages', 'slug' => 'pages.edit', 'group' => 'pages'],
        ['name' => 'Submit Pages For Approval', 'slug' => 'pages.submit_for_approval', 'group' => 'pages'],
        ['name' => 'Review Pages', 'slug' => 'pages.review', 'group' => 'pages'],
        ['name' => 'Approve Pages', 'slug' => 'pages.approve', 'group' => 'pages'],
        ['name' => 'Reject Pages', 'slug' => 'pages.reject', 'group' => 'pages'],
        ['name' => 'Hold Pages', 'slug' => 'pages.hold', 'group' => 'pages'],
        ['name' => 'Publish Pages', 'slug' => 'pages.publish', 'group' => 'pages'],
        ['name' => 'View Briefs', 'slug' => 'briefs.view', 'group' => 'briefs'],
        ['name' => 'Create Briefs', 'slug' => 'briefs.create', 'group' => 'briefs'],
        ['name' => 'Edit Briefs', 'slug' => 'briefs.edit', 'group' => 'briefs'],
        ['name' => 'Submit Briefs For Approval', 'slug' => 'briefs.submit_for_approval', 'group' => 'briefs'],
        ['name' => 'Review Briefs', 'slug' => 'briefs.review', 'group' => 'briefs'],
        ['name' => 'Approve Briefs', 'slug' => 'briefs.approve', 'group' => 'briefs'],
        ['name' => 'Reject Briefs', 'slug' => 'briefs.reject', 'group' => 'briefs'],
        ['name' => 'Hold Briefs', 'slug' => 'briefs.hold', 'group' => 'briefs'],
        ['name' => 'View Onboarding', 'slug' => 'onboarding.view', 'group' => 'onboarding'],
        ['name' => 'Override Onboarding', 'slug' => 'onboarding.override', 'group' => 'onboarding'],
        ['name' => 'Force Complete Onboarding', 'slug' => 'onboarding.force_complete', 'group' => 'onboarding'],
        ['name' => 'View Dashboard Widgets', 'slug' => 'dashboard.widgets.view', 'group' => 'dashboard'],
        ['name' => 'View Dashboard Payouts Widget', 'slug' => 'dashboard.payouts.view', 'group' => 'dashboard'],
        ['name' => 'View Dashboard Onboarding Widget', 'slug' => 'dashboard.onboarding.view', 'group' => 'dashboard'],
        ['name' => 'View Dashboard Content Queue Widget', 'slug' => 'dashboard.content_queue.view', 'group' => 'dashboard'],
        ['name' => 'Create Contract', 'slug' => 'contract.create', 'group' => 'contracts'],
        ['name' => 'Edit Contract', 'slug' => 'contract.edit', 'group' => 'contracts'],
        ['name' => 'Publish Contract', 'slug' => 'contract.publish', 'group' => 'contracts'],
        ['name' => 'Archive Contract', 'slug' => 'contract.archive', 'group' => 'contracts'],
        ['name' => 'View Contract', 'slug' => 'contract.view', 'group' => 'contracts'],
        ['name' => 'Sign Contract', 'slug' => 'contract.sign', 'group' => 'contracts'],
        ['name' => 'Create Guideline', 'slug' => 'guideline.create', 'group' => 'guidelines'],
        ['name' => 'Edit Guideline', 'slug' => 'guideline.edit', 'group' => 'guidelines'],
        ['name' => 'Publish Guideline', 'slug' => 'guideline.publish', 'group' => 'guidelines'],
        ['name' => 'Archive Guideline', 'slug' => 'guideline.archive', 'group' => 'guidelines'],
        ['name' => 'Acknowledge Guideline', 'slug' => 'guideline.acknowledge', 'group' => 'guidelines'],
        ['name' => 'Request Payout', 'slug' => 'payout.request', 'group' => 'finance'],
        ['name' => 'View Payout', 'slug' => 'payout.view', 'group' => 'finance'],
        ['name' => 'Approve Payout', 'slug' => 'payout.approve', 'group' => 'finance'],
        ['name' => 'Reject Payout', 'slug' => 'payout.reject', 'group' => 'finance'],
        ['name' => 'Mark Payout Paid', 'slug' => 'payout.mark_paid', 'group' => 'finance'],
        ['name' => 'View Ledger', 'slug' => 'ledger.view', 'group' => 'finance'],
        ['name' => 'Invite Creator', 'slug' => 'creator.invite', 'group' => 'creator_management'],
        ['name' => 'Remove Creator', 'slug' => 'creator.remove', 'group' => 'creator_management'],
        ['name' => 'Suspend Creator', 'slug' => 'creator.suspend', 'group' => 'creator_management'],
        ['name' => 'Manage Creator Roles', 'slug' => 'creator.manage_roles', 'group' => 'creator_management'],
        ['name' => 'View Contributor Details', 'slug' => 'contributor.details.view', 'group' => 'contributors'],
        ['name' => 'View Contributor Invitations', 'slug' => 'contributor.invitation.view', 'group' => 'contributors'],
        ['name' => 'Resend Contributor Invitations', 'slug' => 'contributor.invitation.resend', 'group' => 'contributors'],
        ['name' => 'Revoke Contributor Invitations', 'slug' => 'contributor.invitation.revoke', 'group' => 'contributors'],
        ['name' => 'View Contributor Capabilities', 'slug' => 'contributor.capabilities.view', 'group' => 'contributors'],
        ['name' => 'Manage Contributor Capabilities', 'slug' => 'contributor.capabilities.manage', 'group' => 'contributors'],
        ['name' => 'View Contributor Onboarding', 'slug' => 'contributor.onboarding.view', 'group' => 'contributors'],
        ['name' => 'View Contributor Activity', 'slug' => 'contributor.activity.view', 'group' => 'contributors'],
        ['name' => 'Manage Site', 'slug' => 'site.manage', 'group' => 'site_administration'],
        ['name' => 'Manage Site Members', 'slug' => 'site.members', 'group' => 'site_administration'],
        ['name' => 'Manage Site Roles', 'slug' => 'site.roles.manage', 'group' => 'site_administration'],
        ['name' => 'Manage Site Permissions', 'slug' => 'site.permissions.manage', 'group' => 'site_administration'],
        ['name' => 'View Violations', 'slug' => 'violation.view', 'group' => 'moderation'],
        ['name' => 'Record Violations', 'slug' => 'violation.record', 'group' => 'moderation'],
        ['name' => 'Resolve Violations', 'slug' => 'violation.resolve', 'group' => 'moderation'],
    ],

    'roles' => [
        'site_admin' => [
            'name' => 'Site Admin',
            'is_system' => true,
            'permissions' => ['*'],
        ],
        'creator' => [
            'name' => 'Creator',
            'is_system' => true,
            'permissions' => [
                'content.create',
                'content.submit',
                'content.edit_own',
                'pages.create',
                'pages.submit_for_approval',
                'pages.edit',
                'payout.request',
                'contract.sign',
                'guideline.acknowledge',
                'onboarding.view',
            ],
        ],
        'reviewer' => [
            'name' => 'Reviewer',
            'is_system' => true,
            'permissions' => [
                'content.review',
                'content.reject',
                'content.approve',
                'pages.view',
                'pages.review',
                'pages.approve',
                'pages.reject',
                'pages.hold',
                'briefs.view',
                'briefs.review',
                'briefs.approve',
                'briefs.reject',
                'briefs.hold',
                'violation.view',
                'violation.record',
            ],
        ],
        'finance' => [
            'name' => 'Finance',
            'is_system' => true,
            'permissions' => ['payout.view', 'payout.approve', 'payout.reject', 'payout.mark_paid', 'ledger.view'],
        ],
        'legal' => [
            'name' => 'Legal',
            'is_system' => true,
            'permissions' => ['contract.create', 'contract.edit', 'contract.publish', 'contract.archive', 'contract.view', 'guideline.create', 'guideline.edit', 'guideline.publish', 'guideline.archive'],
        ],
        'brand_manager' => [
            'name' => 'Brand Manager',
            'is_system' => true,
            'permissions' => ['creator.invite', 'creator.manage_roles', 'onboarding.override', 'site.members', 'violation.view', 'violation.record', 'violation.resolve'],
        ],
    ],

    'legacy_role_map' => [
        'admin' => ['site_role' => 'site_admin', 'permissions' => ['*']],
        'agent' => ['site_role' => 'site_admin', 'permissions' => ['*']],
        'finance' => ['site_role' => 'finance', 'permissions' => ['payout.view', 'payout.approve', 'payout.reject', 'payout.mark_paid', 'ledger.view']],
        'legal' => ['site_role' => 'legal', 'permissions' => ['contract.create', 'contract.edit', 'contract.publish', 'contract.archive', 'contract.view', 'guideline.create', 'guideline.edit', 'guideline.publish', 'guideline.archive']],
        'creator' => ['site_role' => 'creator', 'permissions' => ['content.create', 'content.submit', 'content.edit_own', 'pages.create', 'pages.submit_for_approval', 'pages.edit', 'onboarding.view']],
        'contributor' => ['site_role' => 'creator', 'permissions' => ['content.create', 'content.submit', 'content.edit_own', 'pages.create', 'pages.submit_for_approval', 'pages.edit', 'payout.request', 'contract.sign', 'guideline.acknowledge', 'onboarding.view']],
        'reviewer' => ['site_role' => 'reviewer', 'permissions' => ['content.review', 'content.reject', 'content.approve', 'pages.view', 'pages.review', 'pages.reject', 'pages.approve', 'pages.hold', 'briefs.view', 'briefs.review', 'briefs.reject', 'briefs.approve', 'briefs.hold']],
        'editor' => ['site_role' => 'reviewer', 'permissions' => ['content.review', 'content.reject', 'content.approve', 'pages.view', 'pages.review', 'pages.reject', 'pages.approve', 'pages.hold', 'briefs.view', 'briefs.review', 'briefs.reject', 'briefs.approve', 'briefs.hold', 'violation.view', 'violation.record']],
    ],
];
