<?php

namespace App\Tests\Functional\Controllers;

use App\Models\PageGrid;
use App\Models\PageGridTerritory;
use App\Models\Territory;

class PageGridControllerTest extends FunctionalTestCase
{
    public function testCanListPageGrids()
    {
        $this->createPageGrid(3);

        $response = $this->getForSite('/api/page-grids');

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);

        $this->assertArrayHasKey('success', $data);
        $this->assertArrayHasKey('data', $data);
        $this->assertArrayHasKey('pagination', $data);

        // Check structure of first item if data exists
        if (!empty($data['data'])) {
            $firstItem = $data['data'][0];

            $this->assertArrayHasKey('id', $firstItem);
            $this->assertArrayHasKey('title', $firstItem);
            $this->assertArrayHasKey('slug', $firstItem);
            $this->assertArrayHasKey('layout', $firstItem);
            $this->assertArrayHasKey('columns', $firstItem);
            $this->assertArrayHasKey('is_active', $firstItem);
        }

        $this->assertCount(3, $data['data']);
    }

    public function testCanListPageGridsWithSearch()
    {
        $this->createPageGrid(1, ['title' => 'Featured Properties']);
        $this->createPageGrid(1, ['title' => 'Latest News']);
        $this->createPageGrid(1, ['title' => 'Featured Articles']);

        $response = $this->getForSite('/api/page-grids?search=featured');

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getContent(), true);
        $this->assertCount(2, $data['data']);
    }

    public function testCanListPageGridsWithFilters()
    {
        PageGrid::create([
            'title' => 'Grid 1',
            'slug' => 'grid-1',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED: Array instead of json_encode
            'site_id' => $this->siteId
        ]);

        PageGrid::create([
            'title' => 'Grid 2',
            'slug' => 'grid-2',
            'layout' => 'list',
            'columns' => 1,
            'is_active' => false,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        PageGrid::create([
            'title' => 'Grid 3',
            'slug' => 'grid-3',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        $response = $this->getForSite('/api/page-grids?layout=grid&is_active=1');

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getContent(), true);
        $this->assertCount(2, $data['data']);
    }

    public function testCanCreatePageGrid()
    {
        $data = [
            'title' => 'Test Grid',
            'subtitle' => 'Test Subtitle',
            'layout' => 'grid',
            'columns' => 3,
            'show_excerpt' => true,
            'show_image' => true,
            'show_features' => true,
            'show_actions' => true,
            'pages' => [ // FIXED: Array instead of json_encode
                [
                    'title' => 'Page 1',
                    'slug' => 'page-1',
                    'excerpt' => 'Test excerpt',
                    'url' => '/page-1',
                ]
            ],
            'is_active' => true,
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $this->assertArrayHasKey('success', $responseData);
        $this->assertArrayHasKey('message', $responseData);
        $this->assertArrayHasKey('data', $responseData);

        $gridData = $responseData['data'];

        $this->assertArrayHasKey('id', $gridData);
        $this->assertArrayHasKey('title', $gridData);
        $this->assertArrayHasKey('slug', $gridData);
        $this->assertArrayHasKey('layout', $gridData);
        $this->assertArrayHasKey('columns', $gridData);
        $this->assertArrayHasKey('items', $gridData);

        $this->assertTrue($responseData['success']);
        $this->assertEquals('Test Grid', $gridData['title']);
        $this->assertEquals('grid', $gridData['layout']);

        // Verify in database
        $created = PageGrid::where('title', 'Test Grid')->first();
        $this->assertNotNull($created);
        $this->assertEquals('test-grid', $created->slug);
    }

    public function testCanCreatePageGridWithAutoGeneratedSlug()
    {
        $data = [
            'title' => 'Test Grid',
            'layout' => 'grid',
            'columns' => 3,
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());

        $created = PageGrid::where('title', 'Test Grid')->first();
        $this->assertNotNull($created);
        $this->assertEquals('test-grid', $created->slug);
    }

    public function testCannotCreatePageGridWithInvalidData()
    {
        $data = [
            'title' => 'Test Grid',
            'layout' => 'invalid-layout',
            'columns' => 10, // exceeds max
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(422, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $this->assertArrayHasKey('error', $responseData);
    }

    public function testCanShowPageGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        $response = $this->getForSite("/api/page-grids/{$pageGrid->id}");

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);

        $this->assertTrue($data['success']);
        $this->assertEquals($pageGrid->id, $data['data']['id']);
        $this->assertEquals($pageGrid->title, $data['data']['title']);
        $this->assertEquals($pageGrid->slug, $data['data']['slug']);
    }

    public function testCanShowPageGridBySlug()
    {
        PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        $response = $this->getForSite('/api/page-grids/slug/test-grid');

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('test-grid', $data['data']['slug']);
    }

    public function testReturns404WhenPageGridNotFound()
    {
        $response = $this->getForSite('/api/page-grids/999');

        $this->assertEquals(404, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertFalse($data['success']);
        $this->assertEquals('Page grid not found', $data['message']);
    }

    public function testCanUpdatePageGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Old Title',
            'slug' => 'old-title',
            'layout' => 'grid',
            'columns' => 2,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        $updateData = [
            'title' => 'New Title',
            'columns' => 4,
        ];

        $response = $this->putForSite("/api/page-grids/{$pageGrid->id}", $updateData);

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('New Title', $data['data']['title']);
        $this->assertEquals(4, $data['data']['columns']);

        // Verify in database
        $updated = PageGrid::find($pageGrid->id);
        $this->assertEquals('New Title', $updated->title);
        $this->assertEquals(4, $updated->columns);
    }

    public function testCanCreatePageGridWithDates()
    {
        $data = [
            'title' => 'Seasonal Grid',
            'layout' => 'grid',
            'columns' => 3,
            'start_date' => '2025-01-01 00:00:00',
            'end_date' => '2025-12-31 23:59:59',
            'is_active' => true,
            'site_id' => $this->siteId
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());
        $responseData = json_decode($response->getContent(), true);
        $this->assertEquals($data['start_date'], $responseData['data']['start_date']);
        $this->assertEquals($data['end_date'], $responseData['data']['end_date']);
    }

    public function testCannotCreatePageGridWithInvalidDates()
    {
        $data = [
            'title' => 'Invalid Grid',
            'layout' => 'grid',
            'columns' => 3,
            'start_date' => '2025-12-31 00:00:00',
            'end_date' => '2025-01-01 00:00:00', // End before start
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(422, $response->getStatusCode());
    }

    public function testCanGetPageGridHistory()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [],
            'site_id' => $this->siteId
        ]);

        // Update it to create history
        $this->putForSite("/api/page-grids/{$pageGrid->id}", [
            'title' => 'Updated Grid'
        ]);

        $response = $this->getForSite("/api/page-grids/{$pageGrid->id}/history");

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getContent(), true);
        $this->assertArrayHasKey('success', $data);
        $this->assertArrayHasKey('data', $data);
        $this->assertGreaterThan(0, count($data['data']));
    }

    public function testHistoryTracksPageGridUpdates()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Original Title',
            'slug' => 'original-title',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [],
            'site_id' => $this->siteId
        ]);

        $this->putForSite("/api/page-grids/{$pageGrid->id}", [
            'title' => 'New Title',
            'columns' => 4
        ]);

        $response = $this->getForSite("/api/page-grids/{$pageGrid->id}/history");

        $data = json_decode($response->getContent(), true);

        $latestHistory = $data['data'][0];

        $this->assertEquals('updated', $latestHistory['action']);

        $changes = json_decode($latestHistory['changes'], true);
        $this->assertArrayHasKey('changes', $changes);
        $this->assertEquals('Original Title', $changes['changes']['title']['old']);
        $this->assertEquals('New Title', $changes['changes']['title']['new']);
    }

    public function testCanDeletePageGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        $response = $this->deleteForSite("/api/page-grids/{$pageGrid->id}");

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Page grid deleted successfully', $data['message']);

        // Verify soft delete
        $deleted = PageGrid::find($pageGrid->id);
        $this->assertNull($deleted);
    }

    public function testCanRestorePageGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        // Soft delete the grid
        $pageGrid->delete();

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/restore");

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Page grid restored successfully', $data['message']);

        // Verify restoration
        $restored = PageGrid::find($pageGrid->id);
        $this->assertNotNull($restored);
    }

    public function testCanForceDeletePageGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        $pageGrid->delete();

        $response = $this->deleteForSite("/api/page-grids/{$pageGrid->id}/force");

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Page grid permanently deleted', $data['message']);

        // Verify permanent deletion
        $this->assertNull(PageGrid::find($pageGrid->id));
    }

    public function testCanDuplicatePageGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Original Grid',
            'slug' => 'original-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [],
            'site_id' => $this->siteId
        ]);

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/duplicate");

        $this->assertEquals(201, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Page grid duplicated successfully', $data['message']);
        $this->assertEquals('Original Grid (Copy)', $data['data']['title']);
        $this->assertEquals('original-grid-copy', $data['data']['slug']);

        // Verify in database
        $duplicate = PageGrid::where('slug', 'original-grid-copy')->first();
        $this->assertNotNull($duplicate);

        // Verify history was created for the duplicate
        $historyResponse = $this->getForSite("/api/page-grids/{$duplicate->id}/history");
        $historyData = json_decode($historyResponse->getContent(), true);

        $this->assertGreaterThan(0, count($historyData['data']));
        $this->assertEquals('created', $historyData['data'][0]['action']);
    }

    public function testCanToggleActiveStatus()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/toggle-active");

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals(0, $data['data']['is_active']);

        // Verify in database
        $updated = PageGrid::find($pageGrid->id);
        $this->assertFalse($updated->is_active);
    }

    public function testCanAddPageToGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);

        $pageData = [
            'title' => 'New Page',
            'slug' => 'new-page',
            'excerpt' => 'Page excerpt',
            'url' => '/new-page',
        ];

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/pages", $pageData);

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Page added to grid successfully', $data['message']);

        $pageGrid = PageGrid::find($pageGrid->id);
        $this->assertCount(1, $pageGrid->items);
        $this->assertEquals('New Page', $pageGrid->items[0]['title']);
    }

    public function testCanRemovePageFromGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['title' => 'Page 1', 'slug' => 'page-1'],
                ['title' => 'Page 2', 'slug' => 'page-2'],
            ],
            'site_id' => $this->siteId
        ]);

        $response = $this->deleteForSite("/api/page-grids/{$pageGrid->id}/pages/0");

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);

        $this->assertTrue($data['success']);
        $this->assertEquals('Page removed from grid successfully', $data['message']);

        $pageGrid = PageGrid::find($pageGrid->id);

        $this->assertCount(1, $pageGrid->items);
        $this->assertEquals('Page 2', $pageGrid->items[0]['title']);
    }

    public function testCanUpdatePageInGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['title' => 'Old Title', 'slug' => 'old-slug'],
            ],
            'site_id' => $this->siteId
        ]);

        $updateData = [
            'title' => 'Updated Title',
            'excerpt' => 'Updated excerpt',
        ];

        $response = $this->putForSite("/api/page-grids/{$pageGrid->id}/pages/0", $updateData);

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Page updated successfully', $data['message']);

        $pageGrid = PageGrid::find($pageGrid->id);

        $this->assertEquals('Updated Title', $pageGrid->items[0]['title']);
        $this->assertEquals('Updated excerpt', $pageGrid->items[0]['excerpt']);
    }

    public function testCanReorderPagesInGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['title' => 'Page 1', 'slug' => 'page-1'],
                ['title' => 'Page 2', 'slug' => 'page-2'],
                ['title' => 'Page 3', 'slug' => 'page-3'],
            ],
            'site_id' => $this->siteId
        ]);

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/pages/reorder", [
            'order' => [2, 0, 1]
        ]);

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Pages reordered successfully', $data['message']);

        $pageGrid = PageGrid::find($pageGrid->id);

        $this->assertEquals('Page 3', $pageGrid->items[0]['title']);
        $this->assertEquals('Page 1', $pageGrid->items[1]['title']);
        $this->assertEquals('Page 2', $pageGrid->items[2]['title']);
    }

    public function testPaginationWorksCorrectly()
    {
        for ($i = 1; $i <= 25; $i++) {
            PageGrid::create([
                'title' => "Grid $i",
                'slug' => "grid-$i",
                'layout' => 'grid',
                'columns' => 3,
                'is_active' => true,
                'pages' => [], // FIXED
                'site_id' => $this->siteId
            ]);
        }

        $response = $this->getForSite('/api/page-grids?per_page=10');

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertArrayHasKey('success', $data);
        $this->assertArrayHasKey('data', $data);
        $this->assertArrayHasKey('pagination', $data);

        $pagination = $data['pagination'];
        $this->assertArrayHasKey('current_page', $pagination);
        $this->assertArrayHasKey('last_page', $pagination);
        $this->assertArrayHasKey('per_page', $pagination);
        $this->assertArrayHasKey('total', $pagination);
        $this->assertArrayHasKey('from', $pagination);
        $this->assertArrayHasKey('to', $pagination);

        $this->assertCount(10, $data['data']);
        $this->assertEquals(25, $pagination['total']);
        $this->assertEquals(3, $pagination['last_page']);
    }

    public function testSortingWorksCorrectly()
    {
        // Create records with explicit created_at timestamps
        $zebra = PageGrid::create([
            'title' => 'Zebra',
            'slug' => 'zebra',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);
        // Manually update created_at to ensure proper ordering
        $this->database->query(
            "UPDATE page_grids SET created_at = ? WHERE id = ?",
            [date('Y-m-d H:i:s', strtotime('-3 days')), $zebra->id]
        );

        $alpha = PageGrid::create([
            'title' => 'Alpha',
            'slug' => 'alpha',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);
        $this->database->query(
            "UPDATE page_grids SET created_at = ? WHERE id = ?",
            [date('Y-m-d H:i:s', strtotime('-2 days')), $alpha->id]
        );

        $beta = PageGrid::create([
            'title' => 'Beta',
            'slug' => 'beta',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [], // FIXED
            'site_id' => $this->siteId
        ]);
        $this->database->query(
            "UPDATE page_grids SET created_at = ? WHERE id = ?",
            [date('Y-m-d H:i:s', strtotime('-1 day')), $beta->id]
        );

        // Sort by title ascending
        $response = $this->getForSite('/api/page-grids?sort_by=title&sort_order=asc');

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getContent(), true);
        $this->assertEquals('Alpha', $data['data'][0]['title']);
        $this->assertEquals('Beta', $data['data'][1]['title']);
        $this->assertEquals('Zebra', $data['data'][2]['title']);

        // Sort by created_at descending (most recent first)
        $response = $this->getForSite('/api/page-grids?sort_by=created_at&sort_order=desc');

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getContent(), true);

        // Beta was created most recently (-1 day), so it should be first
        $this->assertEquals('Beta', $data['data'][0]['title']);
        $this->assertEquals('Alpha', $data['data'][1]['title']);
        $this->assertEquals('Zebra', $data['data'][2]['title']);
    }

    public function testCanCreatePageGridWithUseHero()
    {
        $data = [
            'title' => 'Hero Grid',
            'layout' => 'grid',
            'columns' => 3,
            'use_hero' => true,
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());
        $responseData = json_decode($response->getContent(), true);
        $this->assertTrue($responseData['data']['use_hero']);
    }

    public function testCanUpdateUseHeroFlag()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'pages' => [],
            'use_hero' => false,
            'site_id' => $this->siteId
        ]);

        $response = $this->putForSite("/api/page-grids/{$pageGrid->id}", [
            'use_hero' => true
        ]);

        $this->assertEquals(200, $response->getStatusCode());
        $data = json_decode($response->getContent(), true);
        $this->assertEquals(1, $data['data']['use_hero']);

        $updated = PageGrid::find($pageGrid->id);
        $this->assertTrue($updated->use_hero);
    }

    public function testCanCreatePageGridWithMixedItems()
    {
        $data = [
            'title' => 'Mixed Grid',
            'subtitle' => 'Test Subtitle',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'page',
                    'title' => 'Page 1',
                    'slug' => 'page-1',
                    'excerpt' => 'Page excerpt'
                ],
                [
                    'type' => 'author',
                    'name' => 'John Doe',
                    'slug' => 'john-doe',
                    'bio' => 'Author bio'
                ],
                [
                    'type' => 'product',
                    'name' => 'Product 1',
                    'slug' => 'product-1',
                    'price' => '99.99'
                ]
            ],
            'is_active' => true,
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $items = json_decode($responseData['data']['items'], true);

        $this->assertTrue($responseData['success']);
        $this->assertCount(3, $items);
        $this->assertEquals('page', $items[0]['type']);
        $this->assertEquals('author', $items[1]['type']);
        $this->assertEquals('product', $items[2]['type']);
    }

    public function testCanCreatePageGridWithAuthorsOnly()
    {
        $data = [
            'title' => 'Authors Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'author',
                    'name' => 'Author 1',
                    'slug' => 'author-1',
                    'bio' => 'Biography of Author 1',
                    'image' => [
                        'id' => 'img1',
                        'url' => '/images/author1.jpg',
                        'name' => 'author1.jpg',
                        'alt' => 'Author 1 photo'
                    ]
                ],
                [
                    'type' => 'author',
                    'name' => 'Author 2',
                    'slug' => 'author-2',
                    'bio' => 'Biography of Author 2'
                ]
            ],
            'is_active' => true,
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $items = json_decode($responseData['data']['items'], true);

        $this->assertTrue($responseData['success']);
        $this->assertCount(2, $items);
        $this->assertEquals('author', $items[0]['type']);
        $this->assertEquals('Author 1', $items[0]['name']);
    }

    public function testCanCreatePageGridWithProductsOnly()
    {
        $data = [
            'title' => 'Products Grid',
            'layout' => 'grid',
            'columns' => 4,
            'pages' => [
                [
                    'type' => 'product',
                    'name' => 'Product 1',
                    'slug' => 'product-1',
                    'price' => '49.99',
                    'description' => 'Product description',
                    'features' => ['Feature 1', 'Feature 2'],
                    'badge' => [
                        'text' => 'New',
                        'color' => 'success'
                    ]
                ],
                [
                    'type' => 'product',
                    'name' => 'Product 2',
                    'slug' => 'product-2',
                    'price' => '99.99',
                    'location' => 'New York'
                ]
            ],
            'is_active' => true,
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $items = json_decode($responseData['data']['items'], true);
        $this->assertTrue($responseData['success']);
        $this->assertCount(2, $items);
        $this->assertEquals('product', $items[0]['type']);
        $this->assertEquals('Product 1', $items[0]['name']);
        $this->assertEquals('49.99', $items[0]['price']);
    }

    public function testCannotCreatePageGridWithInvalidItemType()
    {
        $data = [
            'title' => 'Invalid Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'invalid_type',
                    'title' => 'Test'
                ]
            ]
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(422, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $this->assertArrayHasKey('error', $responseData);
    }

    public function testCannotCreateAuthorWithoutName()
    {
        $data = [
            'title' => 'Invalid Author Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'author',
                    'bio' => 'Bio without name'
                ]
            ]
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(422, $response->getStatusCode());
    }

    public function testCannotCreateProductWithoutName()
    {
        $data = [
            'title' => 'Invalid Product Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'product',
                    'price' => '99.99'
                ]
            ]
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(422, $response->getStatusCode());
    }

    public function testCanUpdatePageGridWithMixedItems()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Old Grid',
            'slug' => 'old-grid',
            'layout' => 'grid',
            'columns' => 2,
            'is_active' => true,
            'items' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1']
            ],
            'site_id' => $this->siteId
        ]);

        $updateData = [
            'title' => 'Updated Grid',
            'pages' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1'],
                ['type' => 'author', 'name' => 'New Author', 'slug' => 'new-author'],
                ['type' => 'product', 'name' => 'New Product', 'slug' => 'new-product', 'price' => '29.99']
            ]
        ];

        $response = $this->putForSite("/api/page-grids/{$pageGrid->id}", $updateData);

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $items = json_decode($data['data']['items'], true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Updated Grid', $data['data']['title']);
        $this->assertCount(3, $items);
    }

    public function testCanDuplicatePageGridWithMixedItems()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Original Mixed Grid',
            'slug' => 'original-mixed-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1'],
                ['type' => 'author', 'name' => 'Author 1', 'slug' => 'author-1', 'bio' => 'Bio'],
                ['type' => 'product', 'name' => 'Product 1', 'slug' => 'product-1', 'price' => '99.99']
            ],
            'site_id' => $this->siteId
        ]);

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/duplicate");

        $this->assertEquals(201, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $items = json_decode($data['data']['items'], true);
        $this->assertTrue($data['success']);
        $this->assertEquals('Original Mixed Grid (Copy)', $data['data']['title']);
        $this->assertCount(3, $items);

        // Verify all item types are preserved
        $itemTypes = array_column($items, 'type');
        $this->assertContains('page', $itemTypes);
        $this->assertContains('author', $itemTypes);
        $this->assertContains('product', $itemTypes);
    }

    public function testCanAddAuthorToGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [],
            'site_id' => $this->siteId
        ]);

        $authorData = [
            'type' => 'author',
            'name' => 'Jane Doe',
            'slug' => 'jane-doe',
            'bio' => 'Author biography',
            'image' => [
                'id' => 'img1',
                'url' => '/images/jane.jpg',
                'name' => 'jane.jpg',
                'alt' => 'Jane Doe'
            ]
        ];

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/pages", $authorData);

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);

        $pageGrid = PageGrid::find($pageGrid->id);
        $this->assertCount(1, $pageGrid->items);
        $this->assertEquals('author', $pageGrid->items[0]['type']);
        $this->assertEquals('Jane Doe', $pageGrid->items[0]['name']);
    }

    public function testCanAddProductToGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [],
            'site_id' => $this->siteId
        ]);

        $productData = [
            'type' => 'product',
            'name' => 'Amazing Product',
            'slug' => 'amazing-product',
            'price' => '149.99',
            'description' => 'This is an amazing product',
            'features' => ['Feature 1', 'Feature 2', 'Feature 3'],
            'actions' => [
                [
                    'text' => 'Buy Now',
                    'url' => '/buy',
                    'style' => 'primary',
                    'target' => '_self'
                ]
            ]
        ];

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/pages", $productData);

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);

        $pageGrid = PageGrid::find($pageGrid->id);
        $this->assertCount(1, $pageGrid->items);
        $this->assertEquals('product', $pageGrid->items[0]['type']);
        $this->assertEquals('Amazing Product', $pageGrid->items[0]['name']);
        $this->assertEquals('149.99', $pageGrid->items[0]['price']);
    }

    public function testCanRemoveDifferentItemTypesFromGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1'],
                ['type' => 'author', 'name' => 'Author 1', 'slug' => 'author-1'],
                ['type' => 'product', 'name' => 'Product 1', 'slug' => 'product-1', 'price' => '99.99']
            ],
            'site_id' => $this->siteId
        ]);

        // Remove the author (index 1)
        $response = $this->deleteForSite("/api/page-grids/{$pageGrid->id}/pages/1");

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);

        $pageGrid = PageGrid::find($pageGrid->id);
        $this->assertCount(2, $pageGrid->items);
        $this->assertEquals('page', $pageGrid->items[0]['type']);
        $this->assertEquals('product', $pageGrid->items[1]['type']);
    }

    public function testCanReorderMixedItemTypesInGrid()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1'],
                ['type' => 'author', 'name' => 'Author 1', 'slug' => 'author-1'],
                ['type' => 'product', 'name' => 'Product 1', 'slug' => 'product-1', 'price' => '99.99']
            ],
            'site_id' => $this->siteId
        ]);

        $response = $this->postForSite("/api/page-grids/{$pageGrid->id}/pages/reorder", [
            'order' => [2, 0, 1]
        ]);

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);

        $pageGrid = PageGrid::find($pageGrid->id);
        $this->assertEquals('product', $pageGrid->items[0]['type']);
        $this->assertEquals('page', $pageGrid->items[1]['type']);
        $this->assertEquals('author', $pageGrid->items[2]['type']);
    }

    public function testHistoryTracksItemTypeChanges()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1']
            ],
            'site_id' => $this->siteId
        ]);

        // Update to add author and product
        $this->putForSite("/api/page-grids/{$pageGrid->id}", [
            'pages' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1'],
                ['type' => 'author', 'name' => 'New Author', 'slug' => 'new-author'],
                ['type' => 'product', 'name' => 'New Product', 'slug' => 'new-product', 'price' => '99.99']
            ]
        ]);

        $response = $this->getForSite("/api/page-grids/{$pageGrid->id}/history");

        $data = json_decode($response->getContent(), true);

        $this->assertGreaterThan(0, count($data['data']));

        $latestHistory = $data['data'][0];
        $this->assertEquals('updated', $latestHistory['action']);

        $changes = json_decode($latestHistory['changes'], true);
        $this->assertArrayHasKey('changes', $changes);
        $this->assertArrayHasKey('items', $changes['changes']);
    }

    public function testListPageGridsShowsItemsField()
    {
        PageGrid::create([
            'title' => 'Grid with Items',
            'slug' => 'grid-with-items',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1'],
                ['type' => 'author', 'name' => 'Author 1', 'slug' => 'author-1']
            ],
            'site_id' => $this->siteId
        ]);

        $response = $this->getForSite('/api/page-grids');

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $firstItem = $data['data'][0];

        $this->assertArrayHasKey('items', $firstItem);
        $this->assertIsArray($firstItem['items']);
    }

    public function testShowPageGridReturnsItemsWithTypes()
    {
        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [
                ['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1'],
                ['type' => 'author', 'name' => 'Author 1', 'slug' => 'author-1', 'bio' => 'Bio'],
                ['type' => 'product', 'name' => 'Product 1', 'slug' => 'product-1', 'price' => '99.99']
            ],
            'site_id' => $this->siteId
        ]);

        $response = $this->getForSite("/api/page-grids/{$pageGrid->id}");

        $this->assertEquals(200, $response->getStatusCode());

        $data = json_decode($response->getContent(), true);
        $this->assertTrue($data['success']);
        $this->assertArrayHasKey('items', $data['data']);
        $items = json_decode($data['data']['items'], true);
        $this->assertCount(3, $items);

        $types = array_column($items, 'type');
        $this->assertContains('page', $types);
        $this->assertContains('author', $types);
        $this->assertContains('product', $types);
    }

    public function testBackwardsCompatibilityWithPagesField()
    {
        // Test that old 'pages' field still works
        $data = [
            'title' => 'Legacy Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [ // Using old field name
                [
                    'title' => 'Page 1',
                    'slug' => 'page-1'
                ]
            ],
            'is_active' => true,
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $this->assertTrue($responseData['success']);

        // Should have converted to items internally
        $this->assertArrayHasKey('items', $responseData['data']);
    }

    public function testValidatesRequiredFieldsForEachItemType()
    {
        // Test missing title for page
        $pageData = [
            'title' => 'Invalid Page Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'page',
                    'slug' => 'page-1' // Missing title
                ]
            ]
        ];

        $response = $this->postForSite('/api/page-grids', $pageData);
        $this->assertEquals(422, $response->getStatusCode());

        // Test missing name for author
        $authorData = [
            'title' => 'Invalid Author Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'author',
                    'slug' => 'author-1' // Missing name
                ]
            ]
        ];

        $response = $this->postForSite('/api/page-grids', $authorData);
        $this->assertEquals(422, $response->getStatusCode());

        // Test missing name for product
        $productData = [
            'title' => 'Invalid Product Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'product',
                    'price' => '99.99' // Missing name
                ]
            ]
        ];

        $response = $this->postForSite('/api/page-grids', $productData);
        $this->assertEquals(422, $response->getStatusCode());
    }

    public function testCanCreateItemsWithAllOptionalFields()
    {
        $data = [
            'title' => 'Complete Grid',
            'layout' => 'grid',
            'columns' => 3,
            'pages' => [
                [
                    'type' => 'product',
                    'name' => 'Complete Product',
                    'slug' => 'complete-product',
                    'price' => '199.99',
                    'description' => 'Full description',
                    'location' => 'New York',
                    'image' => [
                        'id' => 'img1',
                        'url' => '/images/product.jpg',
                        'name' => 'product.jpg',
                        'alt' => 'Product image',
                        'caption' => 'Product caption'
                    ],
                    'features' => ['Feature 1', 'Feature 2', 'Feature 3'],
                    'actions' => [
                        [
                            'text' => 'Buy Now',
                            'url' => '/buy',
                            'style' => 'primary',
                            'target' => '_blank'
                        ],
                        [
                            'text' => 'Learn More',
                            'url' => '/learn',
                            'style' => 'secondary',
                            'target' => '_self'
                        ]
                    ],
                    'badge' => [
                        'text' => 'Best Seller',
                        'color' => 'success',
                        'background' => '#00ff00'
                    ]
                ]
            ],
            'is_active' => true,
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $this->assertTrue($responseData['success']);

        $items = json_decode($responseData['data']['items'], true);

        $item = $items[0];
        $this->assertEquals('product', $item['type']);
        $this->assertArrayHasKey('features', $item);
        $this->assertArrayHasKey('actions', $item);
        $this->assertArrayHasKey('badge', $item);
        $this->assertArrayHasKey('image', $item);
    }

    public function testCanCreatePageGridWithTerritories()
    {
        $territory1 = Territory::create(['name' => 'Territory 1', 'code' => 'T1', 'is_active' => true, 'site_id' => $this->siteId]);
        $territory2 = Territory::create(['name' => 'Territory 2', 'code' => 'T2', 'is_active' => true, 'site_id' => $this->siteId]);

        $data = [
            'title' => 'Multi-Territory Grid',
            'layout' => 'grid',
            'columns' => 3,
            'territory_ids' => [$territory1->id, $territory2->id],
            'is_active' => true,
            'items' => [['type' => 'page', 'title' => 'Page 1', 'slug' => 'page-1', 'name' => 'Page 1']]
        ];

        $response = $this->postForSite('/api/page-grids', $data);

        $this->assertEquals(201, $response->getStatusCode());

        $responseData = json_decode($response->getContent(), true);
        $this->assertTrue($responseData['success']);

        $pageGrid = PageGrid::find($responseData['data']['id']);
        $territoryIds = PageGridTerritory::where('page_grid_id', $pageGrid->id)
            ->get()
            ->pluck('territory_id');

        $this->assertCount(2, $territoryIds);
        $this->assertContains($territory1->id, $territoryIds);
        $this->assertContains($territory2->id, $territoryIds);
    }

    public function testCanUpdatePageGridTerritories()
    {
        $territory1 = Territory::create(['name' => 'Territory 1', 'code' => 'T1', 'is_active' => true, 'site_id' => $this->siteId]);
        $territory2 = Territory::create(['name' => 'Territory 2', 'code' => 'T2', 'is_active' => true, 'site_id' => $this->siteId]);

        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [],
            'site_id' => $this->siteId
        ]);

        $response = $this->putForSite("/api/page-grids/{$pageGrid->id}", [
            'territory_ids' => [$territory1->id, $territory2->id]
        ]);

        $this->assertEquals(200, $response->getStatusCode());

        $territoryIds = PageGridTerritory::where('page_grid_id', $pageGrid->id)
            ->get()
            ->pluck('territory_id');

        $this->assertCount(2, $territoryIds);
    }

    public function testCanRemoveAllTerritories()
    {
        $territory1 = Territory::create(['name' => 'Territory 1', 'code' => 'T1', 'is_active' => true, 'site_id' => $this->siteId]);

        $pageGrid = PageGrid::create([
            'title' => 'Test Grid',
            'slug' => 'test-grid',
            'layout' => 'grid',
            'columns' => 3,
            'is_active' => true,
            'items' => [],
            'site_id' => $this->siteId
        ]);

        // First assign a territory
        $pageGrid->syncTerritories([$territory1->id]);

        // Then remove all territories
        $response = $this->putForSite("/api/page-grids/{$pageGrid->id}", [
            'territory_ids' => []
        ]);

        $this->assertEquals(200, $response->getStatusCode());

        $territoryIds = PageGridTerritory::where('page_grid_id', $pageGrid->id)
            ->get()
            ->pluck('territory_id');

        $this->assertCount(0, $territoryIds);
    }


    protected function createPageGrid(int $count = 1, array $data = [])
    {
        for ($i = 1; $i <= $count; $i++) {
            PageGrid::create([
                'title' => $data['title'] ?? "Test Page Grid $i",
                'slug' => isset($data['title']) ? $this->slugify($data['title']) : "test-page-grid-$i",
                'layout' => 'grid',
                'columns' => 3,
                'is_active' => true,
                'pages' => [], // FIXED
                'site_id' => $this->siteId
            ]);
        }
    }

    protected function slugify(string $text): string
    {
        $text = preg_replace('~[^\pL\d]+~u', '-', $text);
        $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        $text = preg_replace('~[^-\w]+~', '', $text);
        $text = trim($text, '-');
        $text = preg_replace('~-+~', '-', $text);
        $text = strtolower($text);
        return $text;
    }
}