<?php

declare(strict_types=1);

namespace App\Services\MemberInsights\Newsletters\Relationships;

use App\Enums\MemberInsights\Newsletters\NewsletterRelationType;
use App\Framework\Support\Collection;
use App\Framework\Support\Logger;
use App\Repositories\MemberInsights\Newsletters\NewsletterRelationRepository;
use App\Repositories\Newsletters\NewsletterRepository;
use App\Repositories\Newsletters\SubscriberRepository;

/**
 * Derives and persists relationships between newsletters on a given site.
 *
 * Two-pass strategy:
 *
 * Pass 1 — Category/tag overlap (bootstrap signal)
 *   Compares content_type and page_filters across all active newsletters.
 *   Produces SameCategory and ComplementaryTopic edges deterministically.
 *   Works with zero user data — solves cold-start on day 1.
 *
 * Pass 2 — Co-subscription enrichment
 *   Queries the subscribers table for email overlap between newsletters.
 *   Newsletters where >= CO_SUBSCRIPTION_THRESHOLD of subscribers also
 *   subscribe to another newsletter receive a SameBrand edge (highest weight
 *   because it signals the same audience cluster).
 *   Only runs when there is enough subscriber data to be meaningful.
 *
 * All edges are upserted — re-running this job is safe and idempotent.
 * Manual edges entered by admins (UpsellPremium) are never overwritten
 * because they carry a higher priority value than auto-generated ones.
 *
 * Must NOT:
 *   - Apply recommendation logic.
 *   - Access sessions or request globals.
 *   - Contain heavy query logic (that lives in repositories).
 */
final class NewsletterRelationshipBuilder
{
    /**
     * Minimum fraction of shared subscribers required to derive a
     * co-subscription relationship. 0.30 = 30%.
     */
    private const CO_SUBSCRIPTION_THRESHOLD = 0.30;

    /**
     * Minimum absolute subscriber count before co-subscription pass runs
     * for a given newsletter. Prevents noise on tiny lists.
     */
    private const MIN_SUBSCRIBERS_FOR_CO_SUB = 10;

    public function __construct(
        private readonly NewsletterRepository         $newsletterRepository,
        private readonly NewsletterRelationRepository $relationRepository,
        private readonly SubscriberRepository         $subscriberRepository,
        private readonly Logger                       $logger,
    )
    {
    }

    /**
     * Run both derivation passes for a site and return a summary.
     *
     * @return array{category_edges: int, co_subscription_edges: int}
     */
    public function build(int $siteId): array
    {
        $newsletters = $this->newsletterRepository->getActive($siteId);

        if ($newsletters->count() < 2) {
            $this->logger->info('NewsletterRelationshipBuilder: fewer than 2 active newsletters, skipping', [
                'site_id' => $siteId,
            ]);
            return ['category_edges' => 0, 'co_subscription_edges' => 0];
        }

        $categoryEdges = $this->buildCategoryEdges($newsletters, $siteId);

        $coSubscriptionEdges = $this->buildCoSubscriptionEdges($newsletters, $siteId);

        $this->logger->info('NewsletterRelationshipBuilder: build complete', [
            'site_id' => $siteId,
            'category_edges' => $categoryEdges,
            'co_subscription_edges' => $coSubscriptionEdges,
        ]);

        return [
            'category_edges' => $categoryEdges,
            'co_subscription_edges' => $coSubscriptionEdges,
        ];
    }

    // ── Pass 1: Category / tag overlap ────────────────────────────────────

    /**
     * Compare every newsletter pair on the site.
     * Derives SameCategory when content_type matches.
     * Derives ComplementaryTopic when page_filters share at least one key/value.
     */
    private function buildCategoryEdges(Collection $newsletters, int $siteId): int
    {
        $items = $newsletters->values()->all();
        $count = count($items);
        $edges = 0;

        for ($i = 0; $i < $count; $i++) {
            for ($j = $i + 1; $j < $count; $j++) {
                $a = $items[$i];
                $b = $items[$j];

                $relationType = $this->deriveContentRelation($a, $b);

                if ($relationType === null) {
                    continue;
                }

                // Write both directions so either newsletter can be a source.
                $this->relationRepository->upsertAutoGenerated(
                    newsletterId: (int)$a->id,
                    relatedNewsletterIds: (int)$b->id,
                    relationType: $relationType,
                );

                $this->relationRepository->upsertAutoGenerated(
                    newsletterId: (int)$b->id,
                    relatedNewsletterIds: (int)$a->id,
                    relationType: $relationType,
                );

                $edges += 2;
            }
        }

        return $edges;
    }

    /**
     * Determine the strongest content-based relation type between two newsletters.
     * Returns null if no meaningful overlap exists.
     */
    private function deriveContentRelation(object $a, object $b): ?NewsletterRelationType
    {
        // Exact content_type match → same category
        if (
            !empty($a->content_type)
            && !empty($b->content_type)
            && $a->content_type === $b->content_type
        ) {
            return NewsletterRelationType::SameCategory;
        }

        // page_filters overlap → complementary topic
        $filtersA = is_array($a->page_filters) ? $a->page_filters : [];
        $filtersB = is_array($b->page_filters) ? $b->page_filters : [];

        if ($this->filtersOverlap($filtersA, $filtersB)) {
            return NewsletterRelationType::ComplementaryTopic;
        }

        return null;
    }

    /**
     * Two filter arrays overlap when they share at least one category ID or tag ID.
     * We inspect the 'categories' and 'tags' keys which are integer arrays.
     */
    private function filtersOverlap(array $filtersA, array $filtersB): bool
    {
        foreach (['categories', 'tags'] as $key) {
            $a = $filtersA[$key] ?? [];
            $b = $filtersB[$key] ?? [];

            if (!empty($a) && !empty($b) && !empty(array_intersect($a, $b))) {
                return true;
            }
        }

        return false;
    }

    // ── Pass 2: Co-subscription enrichment ───────────────────────────────

    /**
     * For each newsletter with enough subscribers, check what fraction of
     * its subscribers also subscribe to every other newsletter on the site.
     * Where the fraction meets CO_SUBSCRIPTION_THRESHOLD, upsert a SameBrand edge.
     *
     * SameBrand carries the highest auto-generated score (30) and signals
     * the two newsletters serve the same audience cluster.
     */
    private function buildCoSubscriptionEdges(Collection $newsletters, int $siteId): int
    {
        $edges = 0;

        foreach ($newsletters as $source) {
            $sourceEmails = $this->subscriberRepository
                ->getActiveEmailsForNewsletter((int)$source->id, $siteId);

            $sourceCount = count($sourceEmails);

            if ($sourceCount < self::MIN_SUBSCRIBERS_FOR_CO_SUB) {
                continue;
            }

            foreach ($newsletters as $target) {
                if ($target->id === $source->id) {
                    continue;
                }

                $overlapCount = $this->subscriberRepository
                    ->countEmailOverlap($sourceEmails, (int)$target->id, $siteId);

                $overlapFraction = $overlapCount / $sourceCount;

                if ($overlapFraction < self::CO_SUBSCRIPTION_THRESHOLD) {
                    continue;
                }

                $this->relationRepository->upsertAutoGenerated(
                    newsletterId: (int)$source->id,
                    relatedNewsletterIds: (int)$target->id,
                    relationType: NewsletterRelationType::SameBrand,
                );

                $edges++;
            }
        }

        return $edges;
    }
}